version: '3.8'

services:
  web:
    image: virtual-lab:latest
    container_name: web
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
